# Generated by Django 3.1.4 on 2021-02-15 09:17

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='cur_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('Automotive', 'Automotive'), ('Books & Office Supplies', 'Books & Office Supplies'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Food & Groceries', 'Food & Groceries'), ('Health, Beauty & Perfumes', 'Health, Beauty & Perfumes'), ('Home, Kitchen & Pets', 'Home, Kitchen & Pets'), ('Other', 'Other'), ('Sports, Fitness & Outdoors', 'Sports, Fitness & Outdoors'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Toys, Games & Baby', 'Toys, Games & Baby')], max_length=40),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(upload_to=auctions.models.user_directory_path),
        ),
    ]
